/* Host generator for FreeSCI Pico flash-resident OPL tables.
   Replicates OPLOpenTable() math in fmopl.c at HQ resolution and emits
   const int arrays (SIN_TABLE stored as offsets into TL_TABLE). */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#ifndef PI
#define PI 3.14159265358979323846
#endif

/* HQ quality selection (must match opl2.c OPLBuildTables(FMOPL_ENV_BITS_HQ,
   FMOPL_EG_ENT_HQ) and fmopl.h FMOPL_*_HQ). */
#define ENV_BITS 16
#define EG_ENT   4096

#define SIN_ENT  2048
#define AMS_ENT  512
#define VIB_ENT  512
#define VIB_RATE 256

#define FREQ_BITS 24
#define TL_BITS  (FREQ_BITS + 2)
#define EG_STEP  (96.0 / EG_ENT)

#define TL_MAX   (EG_ENT * 2)
#define EG_DST   (EG_ENT << ENV_BITS)
#define EG_OFF   ((2 * EG_ENT) << ENV_BITS)

#define TL_TABLE_LEN  (TL_MAX * 2)        /* 16384 */
#define SIN_TABLE_LEN (SIN_ENT * 4)       /* 8192  */
#define AMS_TABLE_LEN (AMS_ENT * 2)       /* 1024  */
#define VIB_TABLE_LEN (VIB_ENT * 2)       /* 1024  */
#define ENV_CURVE_LEN (2 * EG_ENT + 1)    /* 8193  */

static int TL_TABLE[TL_TABLE_LEN];
static int SIN_TABLE[SIN_TABLE_LEN];      /* offsets into TL_TABLE */
static int AMS_TABLE[AMS_TABLE_LEN];
static int VIB_TABLE[VIB_TABLE_LEN];
static int ENV_CURVE[ENV_CURVE_LEN];

static void build(void) {
	int s, t, i, j;
	double rate, pom;

	/* total level table */
	for (t = 0; t < EG_ENT - 1; t++) {
		rate = ((1 << TL_BITS) - 1) / pow(10.0, EG_STEP * t / 20);
		TL_TABLE[t] = (int)rate;
		TL_TABLE[TL_MAX + t] = -TL_TABLE[t];
	}
	for (t = EG_ENT - 1; t < TL_MAX; t++)
		TL_TABLE[t] = TL_TABLE[TL_MAX + t] = 0;

	/* sinwave table, stored as TL_TABLE offsets */
	SIN_TABLE[0] = SIN_TABLE[SIN_ENT / 2] = EG_ENT - 1;
	for (s = 1; s <= SIN_ENT / 4; s++) {
		pom = sin(2 * PI * s / SIN_ENT);
		pom = 20 * log10(1 / pom);
		j = (int)(pom / EG_STEP);
		SIN_TABLE[s] = SIN_TABLE[SIN_ENT / 2 - s] = j;
		SIN_TABLE[SIN_ENT / 2 + s] = SIN_TABLE[SIN_ENT - s] = TL_MAX + j;
	}
	for (s = 0; s < SIN_ENT; s++) {
		SIN_TABLE[SIN_ENT * 1 + s] = s < (SIN_ENT / 2) ? SIN_TABLE[s] : EG_ENT;
		SIN_TABLE[SIN_ENT * 2 + s] = SIN_TABLE[s % (SIN_ENT / 2)];
		SIN_TABLE[SIN_ENT * 3 + s] = (s / (SIN_ENT / 4)) & 1 ? EG_ENT : SIN_TABLE[SIN_ENT * 2 + s];
	}

	/* envelope curve */
	for (i = 0; i < EG_ENT; i++) {
		pom = pow(((double)(EG_ENT - 1 - i) / EG_ENT), 8) * EG_ENT;
		ENV_CURVE[i] = (int)pom;
		ENV_CURVE[(EG_DST >> ENV_BITS) + i] = i;
	}
	ENV_CURVE[EG_OFF >> ENV_BITS] = EG_ENT - 1;

	/* LFO AMS */
	for (i = 0; i < AMS_ENT; i++) {
		pom = (1.0 + sin(2 * PI * i / AMS_ENT)) / 2;
		AMS_TABLE[i] = (int)((1.0 / EG_STEP) * pom);
		AMS_TABLE[AMS_ENT + i] = (int)((4.8 / EG_STEP) * pom);
	}
	/* LFO vibrate */
	for (i = 0; i < VIB_ENT; i++) {
		pom = (double)VIB_RATE * 0.06 * sin(2 * PI * i / VIB_ENT);
		VIB_TABLE[i] = (int)(VIB_RATE + (pom * 0.07));
		VIB_TABLE[VIB_ENT + i] = (int)(VIB_RATE + (pom * 0.14));
	}
}

static void emit(const char *name, const int *a, int n) {
	int i;
	printf("const int %s[%d] = {\n", name, n);
	for (i = 0; i < n; i++) {
		printf("%d,", a[i]);
		if ((i & 15) == 15)
			printf("\n");
	}
	printf("\n};\n\n");
}

int main(void) {
	build();
	printf("/* GENERATED by tools/gen_fmopl_tables.c -- DO NOT EDIT.\n");
	printf("   Flash-resident OPL2 tables at HQ resolution:\n");
	printf("   ENV_BITS=%d EG_ENT=%d SIN_ENT=%d AMS_ENT=%d VIB_ENT=%d.\n",
	       ENV_BITS, EG_ENT, SIN_ENT, AMS_ENT, VIB_ENT);
	printf("   SIN_TABLE holds offsets into TL_TABLE (not pointers).\n");
	printf("   Regenerate: cc -O2 tools/gen_fmopl_tables.c -lm -o /tmp/g && /tmp/g > src/sfx/softseq/fmopl_tables.c */\n\n");
	printf("#include \"fmopl_tables.h\"\n\n");
	emit("fmopl_TL_TABLE", TL_TABLE, TL_TABLE_LEN);
	emit("fmopl_SIN_TABLE", SIN_TABLE, SIN_TABLE_LEN);
	emit("fmopl_AMS_TABLE", AMS_TABLE, AMS_TABLE_LEN);
	emit("fmopl_VIB_TABLE", VIB_TABLE, VIB_TABLE_LEN);
	emit("fmopl_ENV_CURVE", ENV_CURVE, ENV_CURVE_LEN);
	return 0;
}
